Update readme file
hasancse91/flutter_getx_template pull request #32
Opened 2022-09-11 12:59 UTC by kazimdsaidul

## Why? (ticket link or issue description)
Give an instruction  to run the project by command link 

## What was done and how?
Dev: `flutter run --flavor dev lib/main_dev.dart`
Prod: `flutter run --flavor dev lib/main_prod.dart`

## Anything special? (optional)

2022-09-11 14:34 UTC, hasancse91 requested changes
Please check the comment.

2022-09-11 14:34 UTC, hasancse91 commented on README.md
> +Prod: `flutter run --flavor dev lib/main_prod.dart`
Should it be `flutter run --flavor prod lib/main_prod.dart`?
I found `--flavor dev` here.

2022-09-17 06:54 UTC, kazimdsaidul commented
Sorry, i mistake. I change it

2022-09-22 00:02 UTC, hasancse91 approved these changes
Thank you for your contribution.

2022-09-22 00:03 UTC, merged